### ISSUE TITLE
Localizing the UI

### ISSUE THREAD

**Issue by rdipardo** [rdipardo/nppHTMLTag#5]
A future version of HTML Tag will be adaptive to the user's language preferences.[^1] The most visible difference will be a localized command menu, e.g.

|    |    |
|:--:|:--:|
|<img width="714" alt="zh-CN" src="https://github.com/rdipardo/nppHTMLTag/assets/59004801/3ebd89f9-6413-42f7-83e2-49ba639ab1d4">|<img width="730" alt="he" src="https://github.com/rdipardo/nppHTMLTag/assets/59004801/2a00a9dc-c751-43e6-9881-1a4bac8638ae">|
|<img width="947" alt="de" src="https://github.com/rdipardo/nppHTMLTag/assets/59004801/f3e2e04c-126d-43c5-aedb-4d72e2a35810">|<img width="918" alt="es-ar" src="https://github.com/rdipardo/nppHTMLTag/assets/59004801/bc1b85f5-94ce-413b-ba3b-ee344ac72e92">|

As explained [on the community forum](https://community.notepad-plus-plus.org/post/87982), the main obstacle for now is a lack of first-class plugin integration. Detecting changed preferences currently requires an application restart. New APIs will probably be essential for any viable implementation. This issue will track any future developments in that area.

In the meantime, contributions to the following work items are welcome:

- [ ] Improve and/or correct the [currently available translations](https://github.com/rdipardo/nppHTMLTag/blob/default/dat/HTMLTag-translations.ini).

- [ ] Add localizations for more languages. Parity with Notepad++ is out of the question, as it currently features 90+.
      The goal is for HTML Tag to support at least half of N++'s catalogue. About 40 would be a good milestone for an initial release.
    
    #### Completed
    + [X] Dutch: dd05730
    

[^1]: __*Not*__ including the About dialog, for a couple of reasons: 1) the text is hard-coded into the form's initialization routines; using resource files instead would bloat an otherwise lightweight component; 2) most of the text is informational and not easily translated.

**Comment by conky77** [comment]
@rdipardo 
if I understood well, your plugin is translated in many languages, but it hasn't translatable yet.
For example If I enter in Italian, I can't see the translation.
Other plugins check the language when N++ starts: is it possible to do the same?

**Comment by rdipardo** [comment]
@conky77 

> Other plugins check the language when N++ starts: is it possible to do the same?

A translatable version of *HTML Tag* is still in development; there's no published version to experiment with (*'spiace!*).

For now it can be tested like this:

1. Visit <https://app.circleci.com/pipelines/github/rdipardo/nppHTMLTag/5/workflows/fbeb8a55-2fd2-478b-9d04-dde827d1644f/jobs/5/artifacts>
2. Select "HTMLTag.dll" (64-bit), or "HTMLTag_unicode.dll" (32-bit)
3. Replace your existing copy of the plugin module with the download
4. Download and save [the translations file] to the same location as the plugin module `$(NPP_LOCATION)\plugins\HTMLTag[_unicode]\HTMLTag-translations.ini`
5. If the native language is already configured, and the translations file has a key for the language, the plugin commands are translated at startup. There's currently no logic to change the menu during usage.


[the translations file]: https://github.com/rdipardo/nppHTMLTag/blob/default/dat/HTMLTag-translations.ini

**Comment by rdipardo** [comment]
[Version 1.5.0](https://github.com/rdipardo/nppHTMLTag/releases/tag/v1.5.0) includes an initial implementation of localized menus for 22 languages.

**Comment by conky77** [comment]
@rdipardo 
with the last version of notepad++ and the last version of the plugin, the menu is not translated. I tried to switch to English, then Italian, close Np++: the menu is still in English
![immagine](https://github.com/user-attachments/assets/6e88a4f7-1fe9-4289-a078-d4e4116c5b0e)

![immagine](https://github.com/user-attachments/assets/bf8bcca4-4983-4ce8-9402-a35886e24fff)




Notepad++ v8.7.1   (64-bit)
Build time : Oct 25 2024 - 04:07:21
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.2)
    DSpellCheck (1.5)
    ERPHelper (1.1.2)
    HexEditor (0.9.12)
    HTMLTag (1.5)
    JsonTools (8.1)
    mimeTools (3.1)
    MultiReplace (4.0.0.19)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.8)
    NppMenuSearch (0.9.6)
    NppPluginOpenHost (1.1)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    SQLinFormNpp64 (6.24.7.15)
    XMLTools (3.1.1.13)

**Comment by conky77** [comment]
Also another plugin "json tools" doesn't switch language, so maybe it depends on n++

**Comment by rdipardo** [comment]
@conky77 

> Local Conf mode : OFF

*Mamma mia!*

Localizations are working for __*portable*__ Notepad++ only &#x2014; i.e., your `nativeLang.xml` must be in `$(LOCAL_NPP_DIR)`, not `%AppData%\Notepad++`:

https://github.com/rdipardo/nppHTMLTag/blob/2426a1a7b4a09c670c75b782d944e3d53a63d382/src/LibNppPlugin/LocalizedPlugin.cpp#L48

The translation code does not run if `nativeLang.xml` isn't found:

https://github.com/rdipardo/nppHTMLTag/blob/2426a1a7b4a09c670c75b782d944e3d53a63d382/src/LibNppPlugin/LocalizedPlugin.cpp#L17-L20

You can use [a development version](https://app.circleci.com/pipelines/github/rdipardo/nppHTMLTag/9/workflows/042d7e17-40df-4d35-8126-59184477477b/jobs/10/artifacts) for now. The fix will be in v1.5.1.

Also, plugin dialogs are not yet translatable; that's a bigger job and will need more translatations from native speakers.
