### ISSUE TITLE
Bug: "automatically decode entities" makes hitting space exit multi-selection

### ISSUE THREAD

**Issue by molsonkiko** [rdipardo/nppHTMLTag#7]
~~Beginning in Notepad++ 8.6.1 or 8.6,~~ hitting space while in a multi-selection or column selection is supposed to enter a space after each caret and stay in multi-selection mode. Thus, I could column select the start of four lines and write `foo bar` four times in a row.

With the `Automatically decode entities` or `Automatically decode Unicode characters` setting turned on, hitting space in multi-selection mode exits the multi-selection.

I imagine that having those settings work for multiple selections simultaneously could get pretty slow, so I think a reasonable resolution to this issue would be to simply suppress those features while the user has multiple selections.

**Comment by rdipardo** [comment]
Try a [development build](https://app.circleci.com/pipelines/github/rdipardo/nppHTMLTag/86/workflows/ae1cc40d-e8eb-4d49-8a4d-5b835cd76b46/jobs/100/artifacts).

---

_**Note:** the `*_unicode` artifacts are 32-bit._

**Comment by molsonkiko** [comment]
Thanks for the quick fix!

**Comment by rdipardo** [comment]
This can stay open until a new release. Can't say when that will be, however.

Not to give too much away, but maintaining somebody else's legacy Pascal code hasn't been as fun as it may have seemed [two years ago](https://sourceforge.net/p/npp-plugins/discussion/725650/thread/08c8e87447).

The goal for now is to port everything to C++ and see if Don Ho will merge the core functionality with mimeTools. If not, at least the code will be intelligible to a greater number of potential contributors.

**Comment by rdipardo** [comment]
Fixed in [1.4.4](https://github.com/rdipardo/nppHTMLTag/releases/tag/v1.4.4), installable *via* Plugins Admin starting with Notepad++ 8.6.5 or newer.
