### ISSUE TITLE
 v1.5.0 TagFinder returns early despite multiple matching tags

### ISSUE THREAD

**Issue by Andr1313** [rdipardo/nppHTMLTag#9]
![Clip](https://github.com/user-attachments/assets/c598cae7-a0c0-4d86-9f06-8687b60c5463)

**Comment by rdipardo** [comment]
Yes, it's a regression. Thanks for finding it.

This build should behave the same as 1.4.4 did: <https://app.circleci.com/pipelines/github/rdipardo/nppHTMLTag/11/workflows/74c2f923-8d7f-4f78-b343-ed19d26ec011/jobs/12/artifacts>

**Comment by Andr1313** [comment]
Thank you very much!

**Comment by Andr1313** [comment]
Alas...
![Clip2](https://github.com/user-attachments/assets/02d73d6e-3e68-4c4e-aaa8-4aa9cb75cd9a)

**Comment by rdipardo** [comment]
Should be fixed now: 
https://app.circleci.com/pipelines/github/rdipardo/nppHTMLTag/12/workflows/59e2132d-ebe5-49e4-8944-8e9a7eb7c722/jobs/13/artifacts

**Comment by Andr1313** [comment]
Yes, everything is fine now.
Thank you very much!

**Comment by rdipardo** [comment]
Superseded by #10
